In [1]:
from selenium import webdriver
import pandas as pd
import html5lib

In [12]:
def Set_up_WebScraping(url):
    
    driver = webdriver.Chrome(r"C:\Users\JourneyQ\OneDrive - kmutnb.ac.th\Desktop\Quick_file\year_2-S_2\softdev-2\week2\chromedriver.exe")
    driver.get(url)
    
    return driver

def get_set50_100_df(driver):
    
    data = driver.page_source
    data_df = pd.read_html(data)[2]
    clean_column = []
    for column in data_df.columns:

        clean_column.append(column.replace("  (Click to sort Ascending)",""))
        
    data_df.columns = clean_column
    data_df = data_df.set_index('หลักทรัพย์')
    return data_df

def get_stock_data(driver,stock,all_stock_dict):
    
    stock = stock.split()[0]
    url_target_financial = "https://www.set.or.th/th/market/product/stock/quote/" + stock + "/historical-trading"
    driver.get(url_target_financial)
    stock_data = driver.page_source
    table_a = pd.read_html(stock_data)[1]
    
    clean_column = []
    for column in table_a:

        clean_column.append(column.replace("  (Click to sort Ascending)",""))
        
    table_a.columns = clean_column
    
    return driver , all_stock_dict

In [10]:
driver = Set_up_WebScraping("https://www.set.or.th/th/market/index/set100/overview")

C:\Users\JourneyQ\AppData\Local\Temp\ipykernel_2180\830543960.py:3: DeprecationWarning: executable_path has been deprecated, please pass in a Service object
  driver = webdriver.Chrome(r"C:\Users\JourneyQ\OneDrive - kmutnb.ac.th\Desktop\Quick_file\year_2-S_2\softdev-2\week2\chromedriver.exe")

In [24]:
stock = 'ACE'
url_target_financial = "https://www.set.or.th/th/market/product/stock/quote/" + stock + "/historical-trading"
driver.get(url_target_financial)
stock_data = driver.page_source
table_a = pd.read_html(stock_data)[1]

clean_column = []
for column in table_a:

    clean_column.append(column.replace("  (Click to sort Ascending)",""))
        
table_a.columns = clean_column
table_a

,วันที่,ราคาเปิด,ราคาสูงสุด,ราคาต่ำสุด,ราคาปิด,เปลี่ยนแปลง,% เปลี่ยนแปลง,ปริมาณ (หุ้น),มูลค่า ('000 บาท)
0,23 ธ.ค. 2565,2.56,2.58,2.54,2.56,0.00,0.00,13693466,35057.19
1,22 ธ.ค. 2565,2.54,2.58,2.54,2.56,0.04,1.59,12610925,32221.61
2,21 ธ.ค. 2565,2.54,2.56,2.52,2.52,-0.02,-0.79,10520203,26581.64
3,20 ธ.ค. 2565,2.62,2.64,2.52,2.54,-0.08,-3.05,33994041,87736.34
4,19 ธ.ค. 2565,2.64,2.66,2.62,2.62,-0.02,-0.76,20825875,54937.82
5,16 ธ.ค. 2565,2.66,2.66,2.64,2.64,-0.02,-0.75,11885382,31501.83
6,15 ธ.ค. 2565,2.66,2.68,2.64,2.66,0.00,0.00,16749918,44542.44
7,14 ธ.ค. 2565,2.68,2.68,2.66,2.66,0.00,0.00,13813977,36832.85
8,13 ธ.ค. 2565,2.66,2.68,2.66,2.66,0.00,0.00,16361143,43629.23
9,09 ธ.ค. 2565,2.68,2.68,2.66,2.66,0.00,0.00,20293338,54246.87
10,08 ธ.ค. 2565,2.68,2.68,2.66,2.66,-0.02,-0.75,16931003,45245.82
11,07 ธ.ค. 2565,2.68,2.70,2.66,2.68,0.00,0.00,14138308,37880.82
12,06 ธ.ค. 2565,2.68,2.70,2.66,2.68,-0.02,-0.74,27961183,74925.90
13,02 ธ.ค. 2565,2.70,2.70,2.68,2.70,0.02,0.75,14337260,38512.66
14,01 ธ.ค. 2565,2.70,2.70,2.68,2.68,-0.02,-0.74,13471679,36222.20
15,30 พ.ย. 2565,2.68,2.70,2.66,2.70,0.02,0.75,14868502,39929.54
16,29 พ.ย. 2565,2.68,2.70,2.66,2.68,0.00,0.00,13902608,37258.61
17,28 พ.ย. 2565,2.68,2.70,2.68,2.68,0.00,0.00,9522506,25523.49
18,25 พ.ย. 2565,2.68,2.70,2.66,2.68,0.00,0.00,16769600,44944.21
19,24 พ.ย. 2565,2.68,2.70,2.68,2.68,0.00,0.00,17189362,46111.18

In [19]:
table_a['หลักทรัพย์'] = "ACE"
table_a

,วันที่,ราคาเปิด,ราคาสูงสุด,ราคาต่ำสุด,ราคาปิด,เปลี่ยนแปลง,% เปลี่ยนแปลง,ปริมาณ (หุ้น),มูลค่า ('000 บาท),หลักทรัพย์
0,23 ธ.ค. 2565,2.56,2.58,2.54,2.56,0.00,0.00,13693466,35057.19,ACE
1,22 ธ.ค. 2565,2.54,2.58,2.54,2.56,0.04,1.59,12610925,32221.61,ACE
2,21 ธ.ค. 2565,2.54,2.56,2.52,2.52,-0.02,-0.79,10520203,26581.64,ACE
3,20 ธ.ค. 2565,2.62,2.64,2.52,2.54,-0.08,-3.05,33994041,87736.34,ACE
4,19 ธ.ค. 2565,2.64,2.66,2.62,2.62,-0.02,-0.76,20825875,54937.82,ACE
5,16 ธ.ค. 2565,2.66,2.66,2.64,2.64,-0.02,-0.75,11885382,31501.83,ACE
6,15 ธ.ค. 2565,2.66,2.68,2.64,2.66,0.00,0.00,16749918,44542.44,ACE
7,14 ธ.ค. 2565,2.68,2.68,2.66,2.66,0.00,0.00,13813977,36832.85,ACE
8,13 ธ.ค. 2565,2.66,2.68,2.66,2.66,0.00,0.00,16361143,43629.23,ACE
9,09 ธ.ค. 2565,2.68,2.68,2.66,2.66,0.00,0.00,20293338,54246.87,ACE
10,08 ธ.ค. 2565,2.68,2.68,2.66,2.66,-0.02,-0.75,16931003,45245.82,ACE
11,07 ธ.ค. 2565,2.68,2.70,2.66,2.68,0.00,0.00,14138308,37880.82,ACE
12,06 ธ.ค. 2565,2.68,2.70,2.66,2.68,-0.02,-0.74,27961183,74925.90,ACE
13,02 ธ.ค. 2565,2.70,2.70,2.68,2.70,0.02,0.75,14337260,38512.66,ACE
14,01 ธ.ค. 2565,2.70,2.70,2.68,2.68,-0.02,-0.74,13471679,36222.20,ACE
15,30 พ.ย. 2565,2.68,2.70,2.66,2.70,0.02,0.75,14868502,39929.54,ACE
16,29 พ.ย. 2565,2.68,2.70,2.66,2.68,0.00,0.00,13902608,37258.61,ACE
17,28 พ.ย. 2565,2.68,2.70,2.68,2.68,0.00,0.00,9522506,25523.49,ACE
18,25 พ.ย. 2565,2.68,2.70,2.66,2.68,0.00,0.00,16769600,44944.21,ACE
19,24 พ.ย. 2565,2.68,2.70,2.68,2.68,0.00,0.00,17189362,46111.18,ACE

In [21]:
table_a.iloc[[1]]

,วันที่,ราคาเปิด,ราคาสูงสุด,ราคาต่ำสุด,ราคาปิด,เปลี่ยนแปลง,% เปลี่ยนแปลง,ปริมาณ (หุ้น),มูลค่า ('000 บาท),หลักทรัพย์
1,22 ธ.ค. 2565,2.54,2.58,2.54,2.56,0.04,1.59,12610925,32221.61,ACE

In [23]:
table_a = table_a.append(table_a)
table_a

C:\Users\JourneyQ\AppData\Local\Temp\ipykernel_2180\740602829.py:1: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  table_a = table_a.append(table_a)

,วันที่,ราคาเปิด,ราคาสูงสุด,ราคาต่ำสุด,ราคาปิด,เปลี่ยนแปลง,% เปลี่ยนแปลง,ปริมาณ (หุ้น),มูลค่า ('000 บาท),หลักทรัพย์
0,23 ธ.ค. 2565,2.56,2.58,2.54,2.56,0.00,0.00,13693466,35057.19,ACE
1,22 ธ.ค. 2565,2.54,2.58,2.54,2.56,0.04,1.59,12610925,32221.61,ACE
2,21 ธ.ค. 2565,2.54,2.56,2.52,2.52,-0.02,-0.79,10520203,26581.64,ACE
3,20 ธ.ค. 2565,2.62,2.64,2.52,2.54,-0.08,-3.05,33994041,87736.34,ACE
4,19 ธ.ค. 2565,2.64,2.66,2.62,2.62,-0.02,-0.76,20825875,54937.82,ACE
...,...,...,...,...,...,...,...,...,...,...
15,30 พ.ย. 2565,2.68,2.70,2.66,2.70,0.02,0.75,14868502,39929.54,ACE
16,29 พ.ย. 2565,2.68,2.70,2.66,2.68,0.00,0.00,13902608,37258.61,ACE
17,28 พ.ย. 2565,2.68,2.70,2.68,2.68,0.00,0.00,9522506,25523.49,ACE
18,25 พ.ย. 2565,2.68,2.70,2.66,2.68,0.00,0.00,16769600,44944.21,ACE
19,24 พ.ย. 2565,2.68,2.70,2.68,2.68,0.00,0.00,17189362,46111.18,ACE

In [26]:
table_a = table_a.append(table_a.iloc[[1]])
table_a

C:\Users\JourneyQ\AppData\Local\Temp\ipykernel_2180\2442751376.py:1: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  table_a = table_a.append(table_a.iloc[[1]])

,วันที่,ราคาเปิด,ราคาสูงสุด,ราคาต่ำสุด,ราคาปิด,เปลี่ยนแปลง,% เปลี่ยนแปลง,ปริมาณ (หุ้น),มูลค่า ('000 บาท)
0,23 ธ.ค. 2565,2.56,2.58,2.54,2.56,0.00,0.00,13693466,35057.19
1,22 ธ.ค. 2565,2.54,2.58,2.54,2.56,0.04,1.59,12610925,32221.61
2,21 ธ.ค. 2565,2.54,2.56,2.52,2.52,-0.02,-0.79,10520203,26581.64
3,20 ธ.ค. 2565,2.62,2.64,2.52,2.54,-0.08,-3.05,33994041,87736.34
4,19 ธ.ค. 2565,2.64,2.66,2.62,2.62,-0.02,-0.76,20825875,54937.82
5,16 ธ.ค. 2565,2.66,2.66,2.64,2.64,-0.02,-0.75,11885382,31501.83
6,15 ธ.ค. 2565,2.66,2.68,2.64,2.66,0.00,0.00,16749918,44542.44
7,14 ธ.ค. 2565,2.68,2.68,2.66,2.66,0.00,0.00,13813977,36832.85
8,13 ธ.ค. 2565,2.66,2.68,2.66,2.66,0.00,0.00,16361143,43629.23
9,09 ธ.ค. 2565,2.68,2.68,2.66,2.66,0.00,0.00,20293338,54246.87
10,08 ธ.ค. 2565,2.68,2.68,2.66,2.66,-0.02,-0.75,16931003,45245.82
11,07 ธ.ค. 2565,2.68,2.70,2.66,2.68,0.00,0.00,14138308,37880.82
12,06 ธ.ค. 2565,2.68,2.70,2.66,2.68,-0.02,-0.74,27961183,74925.90
13,02 ธ.ค. 2565,2.70,2.70,2.68,2.70,0.02,0.75,14337260,38512.66
14,01 ธ.ค. 2565,2.70,2.70,2.68,2.68,-0.02,-0.74,13471679,36222.20
15,30 พ.ย. 2565,2.68,2.70,2.66,2.70,0.02,0.75,14868502,39929.54
16,29 พ.ย. 2565,2.68,2.70,2.66,2.68,0.00,0.00,13902608,37258.61
17,28 พ.ย. 2565,2.68,2.70,2.68,2.68,0.00,0.00,9522506,25523.49
18,25 พ.ย. 2565,2.68,2.70,2.66,2.68,0.00,0.00,16769600,44944.21
19,24 พ.ย. 2565,2.68,2.70,2.68,2.68,0.00,0.00,17189362,46111.18
1,22 ธ.ค. 2565,2.54,2.58,2.54,2.56,0.04,1.59,12610925,32221.61
1,22 ธ.ค. 2565,2.54,2.58,2.54,2.56,0.04,1.59,12610925,32221.61

In [28]:
table_a = pd.concat([table_a, table_a, table_a])

In [29]:
table_a

,วันที่,ราคาเปิด,ราคาสูงสุด,ราคาต่ำสุด,ราคาปิด,เปลี่ยนแปลง,% เปลี่ยนแปลง,ปริมาณ (หุ้น),มูลค่า ('000 บาท)
0,23 ธ.ค. 2565,2.56,2.58,2.54,2.56,0.00,0.00,13693466,35057.19
1,22 ธ.ค. 2565,2.54,2.58,2.54,2.56,0.04,1.59,12610925,32221.61
2,21 ธ.ค. 2565,2.54,2.56,2.52,2.52,-0.02,-0.79,10520203,26581.64
3,20 ธ.ค. 2565,2.62,2.64,2.52,2.54,-0.08,-3.05,33994041,87736.34
4,19 ธ.ค. 2565,2.64,2.66,2.62,2.62,-0.02,-0.76,20825875,54937.82
...,...,...,...,...,...,...,...,...,...
17,28 พ.ย. 2565,2.68,2.70,2.68,2.68,0.00,0.00,9522506,25523.49
18,25 พ.ย. 2565,2.68,2.70,2.66,2.68,0.00,0.00,16769600,44944.21
19,24 พ.ย. 2565,2.68,2.70,2.68,2.68,0.00,0.00,17189362,46111.18
1,22 ธ.ค. 2565,2.54,2.58,2.54,2.56,0.04,1.59,12610925,32221.61
1,22 ธ.ค. 2565,2.54,2.58,2.54,2.56,0.04,1.59,12610925,32221.61