In [1]:
from selenium import webdriver
from selenium.webdriver.common.by import By
import time
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
import pandas as pd
import html5lib

In [2]:
def Set_up_WebScraping(url):
    
    driver = webdriver.Chrome(r"C:\Users\JourneyQ\OneDrive - kmutnb.ac.th\Desktop\Quick_file\year_2-S_2\softdev-2\week2\chromedriver.exe")
    driver.get(url)
    
    return driver

def save_csv(df,name):

    name += ".csv"
    df.to_csv(name,index=False)
    
    return "succes"

def save_excel(df,name):

    name += ".xlsx"
    df.to_excel(name,index=False)
    
    return "succes"

In [3]:
driver = Set_up_WebScraping("https://www.set.or.th/en/market/index/set100/overview")

C:\Users\JourneyQ\AppData\Local\Temp\ipykernel_22900\2693298640.py:3: DeprecationWarning: executable_path has been deprecated, please pass in a Service object
  driver = webdriver.Chrome(r"C:\Users\JourneyQ\OneDrive - kmutnb.ac.th\Desktop\Quick_file\year_2-S_2\softdev-2\week2\chromedriver.exe")

In [5]:
year = ["2023","2022","2021","2020","2019","2018"]

In [6]:
driver.get("https://classic.set.or.th/set/holiday.do?year=" + "2023" + "&language=en&country=US")

In [12]:
data = driver.page_source
data_df = pd.read_html(data)[0]

In [14]:
data_df

,SET Holidays 2023,SET Holidays 2023.1,SET Holidays 2023.2,SET Holidays 2023.3
0,January,Monday,2 January,Substitution for New Year's Eve and New Year's...
1,March,Monday,6 March,Makha Bucha Day
2,April,Thursday,6 April,Chakri Memorial Day
3,NaN,Thursday,13 April,Songkran Festival
4,NaN,Friday,14 April,Songkran Festival
5,May,Monday,1 May,National Labour Day
6,NaN,Thursday,4 May,Coronation Day
7,June,Monday,5 June,Substitution for H.M. Queen Suthida Bajrasudha...
8,July,Friday,28 July,H.M. King Maha Vajiralongkorn Phra Vajiraklaoc...
9,August,Tuesday,1 August,Asarnha Bucha Day
10,NaN,Monday,14 August,Substitution for H.M. Queen Sirikit The Queen ...
11,October,Friday,13 October,H.M. King Bhumibol Adulyadej The Great Memoria...
12,NaN,Monday,23 October,Chulalongkorn Day
13,December,Tuesday,5 December,H.M. King Bhumibol Adulyadej The Great's Birth...
14,NaN,Monday,11 December,Substitution for Constitution Day (Sunday 10 D...

In [21]:
df_holiday = data_df[['SET Holidays 2023.2','SET Holidays 2023.3']]

In [22]:
df_holiday

   SET Holidays 2023.2                                SET Holidays 2023.3
0            2 January  Substitution for New Year's Eve and New Year's...
1              6 March                                    Makha Bucha Day
2              6 April                                Chakri Memorial Day
3             13 April                                  Songkran Festival
4             14 April                                  Songkran Festival
5                1 May                                National Labour Day
6                4 May                                     Coronation Day
7               5 June  Substitution for H.M. Queen Suthida Bajrasudha...
8              28 July  H.M. King Maha Vajiralongkorn Phra Vajiraklaoc...
9             1 August                                  Asarnha Bucha Day
10           14 August  Substitution for H.M. Queen Sirikit The Queen ...
11          13 October  H.M. King Bhumibol Adulyadej The Great Memoria...
12          23 October                                  Chulalongkorn Day
13          5 December  H.M. King Bhumibol Adulyadej The Great's Birth...
14         11 December  Substitution for Constitution Day (Sunday 10 D...

In [19]:
for i in df_holiday['SET Holidays 2023.2']:
    
    i + ' 2023'

C:\Users\JourneyQ\AppData\Local\Temp\ipykernel_22900\4092366475.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_holiday['SET Holidays 2023.2'] = i + ' 2023'

In [23]:
df_holiday

   SET Holidays 2023.2                                SET Holidays 2023.3
0            2 January  Substitution for New Year's Eve and New Year's...
1              6 March                                    Makha Bucha Day
2              6 April                                Chakri Memorial Day
3             13 April                                  Songkran Festival
4             14 April                                  Songkran Festival
5                1 May                                National Labour Day
6                4 May                                     Coronation Day
7               5 June  Substitution for H.M. Queen Suthida Bajrasudha...
8              28 July  H.M. King Maha Vajiralongkorn Phra Vajiraklaoc...
9             1 August                                  Asarnha Bucha Day
10           14 August  Substitution for H.M. Queen Sirikit The Queen ...
11          13 October  H.M. King Bhumibol Adulyadej The Great Memoria...
12          23 October                                  Chulalongkorn Day
13          5 December  H.M. King Bhumibol Adulyadej The Great's Birth...
14         11 December  Substitution for Constitution Day (Sunday 10 D...